apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: frontend
    image: keanu.azurecr.io/frontend-trial
    ports:
    - containerPort: 80
    env:
    - name: REACT_APP_BACKEND_URL
      value: "http://backend-service:8080/"  # Internal URL for the backend service


---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000       # External port
    targetPort: 80   # Container port
